# Generated by Django 3.1.2 on 2021-01-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='song',
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.singer'),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.singer'),
        ),
    ]
