# Generated by Django 3.1.2 on 2021-01-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210105_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.singer'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='songwriter',
        ),
        migrations.AddField(
            model_name='song',
            name='songwriter',
            field=models.ManyToManyField(to='catalog.SongWriter'),
        ),
    ]
